main: com.drewgifford.beacon.BeaconPlugin
name: Beacon
version: 0.1-SNAPSHOT
author: Toadally
api-version: 1.13
commands:
  beacon:
    description: Main command for Beacon
    permission: beacon.use
    aliases: [bcn]


permissions:
  beacon.*:
    description: All beacon commands
    children:
      beacon.use: true
      beacon.modules: true
  beacon.use:
    description: Beacon help menu
  beacon.modules:
    description: View Beacon Modules